### ISSUE TITLE
Sistemazione documento "Dichiarazione Impegni"

### ISSUE THREAD

**Issue by LindyBarby** [NaN1fy/docs#10]
* Aggiungere sezione di suddivisione dei ruoli in base ai membri del gruppo e al ruolo
* Aggiungere sezione di valutazione dei rischi
* Seguire il versionamento portandolo alla 2.0.0
* Portare la deadline a mezzavia: 06/09/2023
- * Considerando i commenti del professore, si è riconsiderata la posizione su una data più sicura sulla consegna del progetto.

**Comment by MartyrVael** [comment]
Verificato

**Comment by Dona-Da** [comment]
verificato
